version: "2"
services:
  the-darksider:
    container_name: the-darksider
    build: .
    restart: always
    volumes:
      - ./:/usr/src/app
    ports:
      - "5000:5000"
    stdin_open: true
  the-darksider-mongo:
    container_name: the-darksider-mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"